---
title: "Homework_3"
format: html
editor: visual
---

## Library package

```{r}
library(sf)
library(here)
library(janitor)
library(tidyverse)
library(terra)
library(ggplot2)
```

```{r}
spain <- sf::st_read("/Users/xfang/Desktop/UCL PHD/PGTA/CASA GIS/Week3/gadm41_ESP.gpkg",
                      layer='ADM_ADM_0')

world_cities <- sf::st_read("/Users/xfang/Desktop/UCL PHD/PGTA/CASA GIS/Week3/World_Cities/World_cities.shp")

ssp1 <-terra::rast("/Users/xfang/Desktop/UCL PHD/PGTA/CASA GIS/Week3/wc2.1_2.5m_tmax_ACCESS-CM2_ssp126_2021-2040.tif")

ssp1_mean <- mean(ssp1)

ssp5 <-terra::rast("/Users/xfang/Desktop/UCL PHD/PGTA/CASA GIS/Week3/wc2.1_2.5m_tmax_ACCESS-CM2_ssp585_2021-2040.tif")
```

## Filter cities

```{r}
spanish_cities <- world_cities %>%
  janitor::clean_names()%>%
  dplyr::filter(cntry_name=="Spain")
```

## Crop and master raster

```{r}
####ssp1

spain_diff <- ssp1 %>%
  # now crop our temp data to the extent
  terra::crop(.,spain)
exact_spain <- spain_diff %>%
  terra::mask(.,spain)
###ssp5

spain_diff5 <- ssp5 %>%
  # now crop our temp data to the extent
  terra::crop(.,spain)

exact_spain5 <- spain_diff5 %>%
  terra::mask(.,spain)
```

## Subtract rasters

```{r}
#### sub
diff_climate_model <- exact_spain5 - exact_spain 
```

## Rename and rejoin the data from month

```{r}
month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

names(diff_climate_model) <- month

spain_city_diff<- terra::extract(diff_climate_model, spanish_cities)
```

## Join the extracted data back to the point dataset

```{r}
spanish_cities_join_ID <- spanish_cities %>%
  dplyr::mutate(join_id= 1:n())
```

```{r}
spain_city_diff2 <- spanish_cities_join_ID%>%
  dplyr::left_join(.,
            spain_city_diff,
             by = c("join_id" = "ID"))
```

## Join

```{r}
spain_city_diff2 <- spanish_cities_join_ID%>%
  dplyr::left_join(.,
            spain_city_diff,
             by = c("join_id" = "ID"))
```

## Drop the geometry and make a facet plot of differences per month

```{r}
# all cities in spain where there is data

city_climate_diff <- spain_city_diff2 %>%
  dplyr::select(c(,16:27))%>%
  sf::st_drop_geometry(.)%>%
  dplyr::as_tibble()

tidy_city_diff <- city_climate_diff %>%
  tidyr::pivot_longer(everything(), 
               names_to="Months", 
               values_to="temp_diff")

facet_plot <- tidy_city_diff %>%
  dplyr::mutate(Months = factor(Months, levels = c("Jan","Feb","Mar",
                                            "Apr","May","Jun",
                                            "Jul","Aug","Sep",
                                            "Oct","Nov","Dec")))
```

## Facet plot

```{r}
plot<-ggplot(facet_plot, aes(x=temp_diff, na.rm=TRUE))+
  geom_histogram(color="black", binwidth = .1)+
  labs(title="ggplot2 faceted difference in climate scenarios of max temp", 
       x="Temperature",
       y="Frequency")+
  facet_grid(Months ~ .)+
  theme(plot.title = element_text(hjust = 0.5))

plot
```
